### ISSUE TITLE
Generation of TalkSet/lists_in

### ISSUE THREAD

**Issue by zjr954** [TaoRuijie/TalkNet_ASD#18]
As I want to generate TalkSet with different data from Vox and LRS3, I wonder if you could provide the code to generate the three lists(Vox_list.txt, LRS3_S_list.txt, LRS3_ST_list.txt), thank you very much!

**Comment by TaoRuijie** [comment]
Ah sorry I did not save that code since that is very redundancy. I may provide my pipeline for you as the ref:

1. In voxceleb2, just pick some utterance from the whole dataset, no restrict. To increase the diversity you may select more speaker.
2. In LRS3, I use VAD in Kaldi to find the slient frames, then the video contains the slient clips (which is at least > 1s ) is selected to generate the LRS3_S_List.txt, more specificially, I crop the slient clips.
3. Meanwhile, for the data in LRS3_S_List, I randomly pick one speaking clip before or after this slient part, the combination of these two parts can be used for LRS3_ST_List.txt, which is -> Slient + True (ST).

**Comment by zjr954** [comment]
Thanks for your reply and also for the neat code!
