### ISSUE TITLE
Is it possible to use different fps and sample rate than 25 and 16000

### ISSUE THREAD

**Issue by asrlhhh** [TaoRuijie/TalkNet_ASD#40]
Hi, first of all, thank you for providing the codes, I found it very helpful and has tested it on a set of youtube videos with high quality result. 

One thing I am wondering is, if there is a way to make the minimal change to let the code inference on arbitrary fps and sample rate. Or is the model trained in a way that it can only ran on a certain combination of (fps, sample rate)?

**Comment by TaoRuijie** [comment]
For the demoTalkNet, it can handle any fps and sr,

So similarly for evaluation only, you can do the preprocess to resample your input video to the same fps and sr.

Btw, I remember the fps of training set (AVA)is not fixed, so this problem ought already be solved.
See here: https://github.com/TaoRuijie/TalkNet-ASD/blob/main/dataLoader.py#L40

As a conclusion, I believe the model can handle the different fps, for different audio sr, I suggest you to resample the input waveform since that is the most efficient solution I know.
