### ISSUE TITLE
Overlapped speech performance

### ISSUE THREAD

**Issue by jayakrishnanmm** [TaoRuijie/TalkNet_ASD#43]
Hi,
I did check this with a video  where 2 speakers speaking at the same time. It can detect only one speech at a time.

**Comment by TaoRuijie** [comment]
The performance of TalkNet may decease for the overlapped speech. 'Can detect only one speech' is not true since the detection for two speakers are INDEPENDENT. In another word, it is possible that there are >=2 green boxes on the screen. While the performance may not robust for that difficult condition.

**Comment by jayakrishnanmm** [comment]
Understood. Perhaps, adding some speaker information in the embedding may help. 
( Another point : when I remove the average smoothing, I could see some improvement. Is this verified  on your side? )

**Comment by TaoRuijie** [comment]
I notice the results are similar in my experiments? Yes they are similar I also find.
