### ISSUE TITLE
face detection models

### ISSUE THREAD

**Issue by SunghwanHong** [TaoRuijie/TalkNet_ASD#5]
I first would like to thank you for making this amazing work and code publicly available. This work will definitely help my future research. 

I have a minor question about face detection model, and i'm wondering if other better or even sota face detection models could improve the performance of demo? would it be compatible to talknet_ASD if I use other face detection model? 

thank you!

**Comment by TaoRuijie** [comment]
Thanks for your interest! I am glad about that.

For the active speaker detection task, the face is already provided, the task is based on the provided face and the audio to do the prediction, so I think a better face detection method will not get better results.

But for this demo, yes you are right, if you have a better face detection model, some small faces can be detected so that you can further perform active speaker detection based on that. Notice that only the face detection results will be better, the ASD result will not affect too much I think.

For a better face detection model. I once tried 'Insightface', it can work well with our TalkNet model and detect the small face, but I did not save that code. The link is here: 'https://github.com/deepinsight/insightface'. You can replace the 'inference_video' function in demoTalkNet.py with their insight_face model.

In another word, if other face detection models can provide a similar detected face area, the ASD performance will be similar. But if the area is not very similar, I am not sure our pretrain model can still work.

**Comment by SunghwanHong** [comment]
Thank you for the super fast and detailed reply! I will try the other face detection models but start with the insightface as you kindly suggested! I will close the comment as my question is solved
